version: "3.9"

services:
  backend:
    build: ./be
    container_name: expense-backend
    ports:
      - "8000:8000"
    volumes:
      - ./be/app/database.json:/app/app/database.json
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./fe
    container_name: expense-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
